# permissions for end users to view batchjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: batchjob-viewer-role
rules:
- apiGroups:
  - batchjob.gcr.io.gcr.io
  resources:
  - batchjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batchjob.gcr.io.gcr.io
  resources:
  - batchjobs/status
  verbs:
  - get
