# permissions for end users to edit batchjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: batchjob-editor-role
rules:
- apiGroups:
  - batchjob.gcr.io.gcr.io
  resources:
  - batchjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batchjob.gcr.io.gcr.io
  resources:
  - batchjobs/status
  verbs:
  - get
