#! /bin/bash

cluster_name=$(gcloud container clusters list --format="value(name)")
pool_name=$(gcloud container clusters list --format="value(nodePools[0].name)")
zone_name=$(gcloud container clusters list --format="value(location)")

if [ $1 == "up" ]
then
gcloud container clusters resize $cluster_name --node-pool $pool_name --num-nodes 3 --zone $zone_name --quiet
elif [ $1 == "down" ]
then
gcloud container clusters resize $cluster_name --node-pool $pool_name --num-nodes 0 --zone $zone_name --quiet
else
echo "Either up or down"
fi